In [1]:
gamma = 0.99

gamma ** 0

1.0

In [3]:
a = [("a", "b", "c"), ("d", "e", "f")]
for i, (x,y,z) in enumerate(a):
    print(i,x,y,z)

0 a b c
1 d e f


In [4]:
a_list = [0, 1, 2, 3, 4]
print(a_list[-2])

3


In [5]:
import numpy as np

x = np.array([1., 2., 3.])
x

array([1., 2., 3.])

In [6]:
np.array([x])

array([[1., 2., 3.]])

In [1]:
def get_env_type(env_name):
    index = env_name.find("_")
    if index == -1:
        return env_name
    return env_name[:index]

In [5]:
get_env_type("gym_ppo_sac")

'gym'

In [6]:
def get_env_id(env_name):
    index = env_name.find("_")
    if index == -1 or index == len(env_name) - 1:
        return ""
    return env_name[index + 1:]

In [7]:
get_env_id("gym_ppo_sac")

'ppo_sac'

In [8]:
from datetime import datetime

# 获取当前时间
now = datetime.now().strftime("%Y/%m/%d/%H:%M")

# 格式化为指定字符串
print(now)  # 输出示例：2025/07/13/11:23

2025/07/13/11:24


In [13]:
import random

random.seed(40)
print(random.random())
print(random.random())

random.seed(40)
print(random.random())
print(random.random())

0.4586067093870614
0.87786790373901
0.4586067093870614
0.87786790373901


In [3]:
import torch

logits = torch.randn(5, 4)
print(logits)

tensor([[ 0.5848,  0.7378, -0.7339,  1.9564],
        [-0.5180,  0.1761,  0.6945,  0.0887],
        [-1.0532,  2.1076, -0.2736, -1.1283],
        [-0.1555,  1.2585,  0.4898, -0.7288],
        [ 0.8346, -0.1941,  2.1430,  0.0954]])


In [9]:
import torch

logits = torch.randn(5, 4)
print(f"Logits shape: {logits.shape}")  # 输出: torch.Size([5, 4])

mean, std = torch.chunk(logits, chunks=2, dim=-1)
std = torch.abs(std)
print(f"Mean shape: {mean.shape}")      # 输出: torch.Size([5, 2])
print(f"Std shape: {std.shape}")        # 输出: torch.Size([5, 2])

gauss_distribution = torch.distributions.Independent(
    base_distribution=torch.distributions.Normal(mean, std),
    reinterpreted_batch_ndims=1,
)

# 查看分布的批量维度和事件维度
print(f"Batch shape: {gauss_distribution.batch_shape}")  # 输出: torch.Size([5])
print(f"Event shape: {gauss_distribution.event_shape}")  # 输出: torch.Size([2])

Logits shape: torch.Size([5, 4])
Mean shape: torch.Size([5, 2])
Std shape: torch.Size([5, 2])
Batch shape: torch.Size([5])
Event shape: torch.Size([2])


In [16]:
# 上面是由策略网络生成的 logits 导出来的动作的分布（每个样本都有2个动作维度上的均值与标准差）
action_sample = torch.randn(5, 2)  #  生成 5 个动作样本（只能是5个，因为gauss_distribution的batch_shape=(5,)），动作的维度是2
gauss_distribution.log_prob(action_sample)

tensor([-355.1440,   -3.8576,   -2.7260, -100.1602,   -2.5839])

In [14]:
gauss_distribution.entropy()

tensor([ 1.1452,  3.5128, -0.1248,  0.5330,  3.5672])

In [17]:
gauss_distribution.sample()

tensor([[-0.6518, -1.9213],
        [ 2.0678,  1.2124],
        [ 0.4446,  0.2445],
        [ 1.0378, -1.6959],
        [-2.1535, -0.8280]])

In [19]:
torch.zeros_like(std).sum(-1)

tensor([0., 0., 0., 0., 0.])

In [20]:
dict1 = dict()

dict2 = dict1.copy()

dict2["nums"] = 1

print(dict2)

{'nums': 1}


In [21]:
print(dict1)

{}


In [22]:
hidden_sizes = [64, 64]

list(hidden_sizes)

[64, 64]

In [23]:
[3] + list(hidden_sizes) + [1]

[3, 64, 64, 1]

In [24]:
layers = hidden_sizes + hidden_sizes
layers

[64, 64, 64, 64]

In [28]:
a = torch.randn(1, 2)
b = torch.abs(torch.randn(1, 2))
print(a)
print(b)
print(torch.cat((a, b), dim=-1))

tensor([[-1.0153,  0.3354]])
tensor([[0.5266, 1.3232]])
tensor([[-1.0153,  0.3354,  0.5266,  1.3232]])


In [29]:
torch.nn.functional.softplus(b) 

tensor([[0.9907, 1.5593]])

In [30]:
(1+1)

2